create table if not exists books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  description text not null,
  cover_image text not null,
  start_date date not null,
  finish_date date not null
);

create table if not exists comments (
  id bigint generated by default as identity primary key,
  name text not null,
  content text not null,
  created_at timestamp with time zone default now()
);

create table if not exists votes (
  id bigint generated by default as identity primary key,
  book_id bigint references books(id) on delete cascade,
  created_at timestamp with time zone default now()
);

create table if not exists meetings (
  id bigint generated by default as identity primary key,
  date date not null,
  time text not null,
  location text not null,
  notes text
);

create table if not exists schedule (
  id bigint generated by default as identity primary key,
  week text not null,
  pages text not null,
  date date not null
);
